In [89]:
import pandas as pd #to load json data to dataframe and iterate,manipulate through json data

In [90]:
#loads data to dataframe -> SearchData and displays first 100 of them
SearchData = pd.read_json('searches.json', lines=True)
SearchData.head(100)

    is_instructor  login_count  search_count       uid
0            True            1             2   6061521
1           False            4             0  11986457
2           False            1             0  15995765
3            True            3             0   9106912
4           False            1             0   9882383
5           False            1             0   5333200
6           False            2             0   3583107
7            True            1             0  11760157
8           False            3             0  13150423
9           False            4             2   8004609
10          False            1             3  13536345
11          False            2             4     52868
12          False            6             0   9613243
13           True           14             0  12986377
14           True            1             0   9792541
15          False            4             0   2815244
16          False            7             0  13320527
17          False            1             0   5651994
18          False            1             0  12260537
19           True            7             0  14915463
20           True            7             1   8228927
21           True            1             0   3378724
22          False            1             0   5936973
23           True            4             0   8373533
24          False            1             0  16102156
25          False            4             2   9185533
26           True            4             0   8905420
27          False            1             1   9954854
28          False            6             0  14133079
29          False            1             0   4716739
..            ...          ...           ...       ...
70          False            1             0  15299641
71           True            1             0  16691979
72          False            3             0   6026021
73          False            1             0   5573213
74          False            2             0   7248535
75          False            3             0  14341169
76           True            3             2    268430
77          False            2             0   1082427
78           True            4             0  11360517
79           True            2             1   3919480
80          False            1             0   8186038
81           True            1             0   4691263
82           True            1             0   7355273
83          False            2             1  13945044
84          False            2             0   8648947
85           True            2             2  14955604
86           True            3             1  10372718
87          False            2             0  13124596
88          False            1             0  13170480
89           True            1             2  10530538
90          False            1             3   8024978
91           True            3             0  15491559
92          False            1             0  13825496
93          False            2             0   4197889
94          False            5             0   9722213
95          False            6             0  14629029
96          False            1             0  13485368
97          False            2             0   9656655
98          False            5             0  14759972
99           True            1             1  11164560

[100 rows x 4 columns]

In [96]:
#creating a dictionary of users who were shown the design B 
#containing user id (uid) as key & 
#number of times the user used the search feature (search_count)as value
b_user = {}
for index, row in SearchData.iterrows():
    b = row['uid']
    if(b%2 != 0):
        b_user[b] = row['search_count']
b_user

{39043: 0,
 174623: 0,
 175145: 0,
 203495: 0,
 252639: 0,
 325327: 0,
 351701: 0,
 368693: 0,
 429071: 0,
 509223: 0,
 547507: 0,
 596881: 0,
 608185: 0,
 659849: 0,
 674805: 5,
 699035: 0,
 800163: 0,
 853849: 0,
 917351: 0,
 955085: 0,
 1045725: 0,
 1082427: 0,
 1112901: 3,
 1141181: 0,
 1177099: 0,
 1188165: 0,
 1202645: 0,
 1203395: 0,
 1215461: 0,
 1400519: 0,
 1440233: 0,
 1475209: 0,
 1478415: 0,
 1547629: 0,
 1572895: 2,
 1585489: 2,
 1638057: 0,
 1638829: 0,
 1657315: 2,
 1668679: 0,
 1724865: 0,
 1791653: 3,
 2013311: 0,
 2036945: 0,
 2043101: 0,
 2180213: 0,
 2183257: 0,
 2321009: 0,
 2327303: 0,
 2368013: 9,
 2615111: 1,
 2730735: 0,
 2849545: 0,
 2898229: 3,
 3013413: 0,
 3372619: 0,
 3381743: 0,
 3400195: 0,
 3402261: 0,
 3469933: 4,
 3494291: 2,
 3522037: 0,
 3544903: 0,
 3546309: 1,
 3583107: 0,
 3596125: 1,
 3691369: 5,
 3701785: 3,
 3754509: 0,
 3761361: 1,
 3793213: 0,
 3857555: 0,
 3942521: 0,
 4039745: 0,
 4068379: 6,
 4120397: 0,
 4197889: 0,
 4310571: 1,
 4333605: 1,
 4362637: 0,
 4573973: 0,
 4598877: 0,
 4644383: 1,
 4691263: 0,
 4706731: 1,
 4716739: 0,
 4739021: 1,
 4781429: 0,
 4892375: 2,
 4952803: 0,
 4953859: 0,
 5026247: 0,
 5125167: 0,
 5233089: 0,
 5377369: 0,
 5454807: 1,
 5501249: 0,
 5543603: 0,
 5573213: 0,
 5696405: 2,
 5785997: 0,
 5864293: 0,
 5873655: 0,
 5877743: 3,
 5936973: 0,
 5958561: 0,
 6026021: 0,
 6059017: 1,
 6061521: 2,
 6184331: 5,
 6206339: 1,
 6312797: 0,
 6454817: 0,
 6491897: 1,
 6531675: 1,
 6542271: 0,
 6593337: 2,
 6595557: 0,
 6598291: 0,
 6625293: 0,
 6655537: 0,
 6753317: 0,
 6773067: 0,
 6778441: 0,
 6779627: 0,
 6799521: 1,
 6805047: 2,
 6810415: 0,
 6941709: 0,
 6954951: 0,
 6980579: 1,
 7083145: 0,
 7089303: 0,
 7119971: 0,
 7239517: 3,
 7248535: 0,
 7355273: 0,
 7362405: 3,
 7479185: 0,
 7491089: 0,
 7643715: 0,
 7651699: 0,
 7690987: 0,
 7810455: 1,
 7861767: 1,
 7883105: 1,
 7908287: 1,
 7978969: 1,
 8004609: 2,
 8026425: 0,
 8044609: 0,
 8053137: 0,
 8062009: 5,
 8090071: 0,
 8102781: 0,
 8117747: 0,
 8202015: 0,
 8226619: 0,
 8228927: 1,
 8233513: 1,
 8300037: 0,
 8339837: 0,
 8362133: 0,
 8368537: 0,
 8373533: 0,
 8420355: 2,
 8448865: 8,
 8473959: 3,
 8527725: 0,
 8553543: 0,
 8574693: 0,
 8574817: 0,
 8648947: 0,
 8698521: 0,
 8703823: 0,
 8735657: 0,
 8764885: 1,
 8839893: 0,
 8942009: 0,
 8976511: 1,
 8981199: 0,
 8992233: 2,
 9036705: 0,
 9052389: 0,
 9061607: 3,
 9095243: 0,
 9164081: 1,
 9185533: 2,
 9220815: 4,
 9237691: 1,
 9289541: 0,
 9290175: 0,
 9310769: 0,
 9542055: 0,
 9557487: 4,
 9613243: 0,
 9656655: 0,
 9722213: 0,
 9792541: 0,
 9796147: 0,
 9803637: 1,
 9855721: 0,
 9871311: 0,
 9882383: 0,
 10091733: 0,
 10141047: 0,
 10148905: 0,
 10291383: 0,
 10396621: 0,
 10456709: 0,
 10476521: 0,
 10494237: 6,
 10528667: 0,
 10561621: 0,
 10657397: 0,
 10689275: 0,
 10717421: 0,
 10740849: 0,
 10787913: 2,
 10841477: 1,
 11000567: 1,
 11025873: 0,
 11074349: 2,
 11094049: 0,
 11354021: 0,
 11360517: 0,
 11562931: 0,
 11566267: 2,
 11760157: 0,
 11855669: 0,
 11858437: 0,
 11894451: 4,
 11912365: 1,
 11986457: 0,
 12026355: 0,
 12069041: 1,
 12077989: 1,
 12182293: 0,
 12205217: 4,
 12231197: 0,
 12260537: 0,
 12339949: 4,
 12360565: 1,
 12370203: 0,
 12428923: 0,
 12458209: 0,
 12462283: 0,
 12504661: 0,
 12613723: 0,
 12634393: 1,
 12640601: 0,
 12665409: 0,
 12709365: 1,
 12763079: 9,
 12774291: 0,
 12787783: 0,
 12815173: 6,
 12818017: 0,
 12822945: 0,
 12857921: 0,
 12866967: 0,
 12960923: 0,
 12968885: 3,
 12970825: 0,
 12986377: 0,
 13005291: 0,
 13033699: 0,
 13076079: 0,
 13081603: 1,
 13102925: 0,
 13150423: 0,
 13206473: 0,
 13294389: 0,
 13311817: 0,
 13320527: 0,
 13333323: 0,
 13519545: 0,
 13536345: 3,
 13539989: 0,
 13578367: 0,
 13635125: 0,
 13707991: 2,
 13789277: 4,
 13822965: 0,
 13885501: 0,
 13946647: 0,
 14040957: 0,
 14079919: 0,
 14086179: 0,
 14128599: 0,
 14133079: 0,
 14197405: 0,
 14215627: 2,
 14227871: 1,
 14240595: 0,
 14256929: 0,
 14341169: 0,
 14368713: 0,
 14407265: 1,
 14426215: 0,
 14480189: 0,
 14485631: 0,
 14496787: 0,
 14629029: 0,
 14780717: 3,
 14838641: 0,
 14856901: 0,
 14891655: 1,
 14901043: 3,
 14905733: 0,
 14915463: 0,
 14965621: 0,
 15103435: 0,
 15150247: 0,
 15171509: 0,
 15198335: 0,
 15254131: 9,
 15299641: 0,
 15310209: 1,
 15338567: 1,
 15339771: 0,
 15390031: 0,
 15432377: 0,
 15433187: 0,
 15445045: 0,
 15491559: 0,
 15589987: 0,
 15646415: 0,
 15666401: 0,
 15678809: 0,
 15701977: 0,
 15717813: 1,
 15756593: 1,
 15930865: 0,
 15995765: 0,
 16035315: 1,
 16111503: 0,
 16141315: 4,
 16152189: 3,
 16164763: 1,
 16170095: 0,
 16189843: 2,
 16429119: 0,
 16583791: 0,
 16619457: 0,
 16672859: 0,
 16691979: 0,
 16775557: 0}

In [92]:
#creating a dictionary of users who were shown the design A 
#containing user id (uid) as key & 
#number of times the user used the search feature (search_count)as value
a_user = {}
for index, row in SearchData.iterrows():
    a = row['uid']
    if(a%2 == 0):
        a_user[a] = row['search_count']
a_user

{8134: 2,
 52868: 4,
 87006: 0,
 174594: 8,
 193986: 0,
 204924: 0,
 268430: 2,
 270944: 3,
 311808: 0,
 325848: 0,
 387824: 2,
 458564: 0,
 495192: 0,
 596434: 0,
 866028: 0,
 1032514: 2,
 1037096: 3,
 1079304: 0,
 1108670: 9,
 1117598: 2,
 1184250: 0,
 1205992: 2,
 1218512: 0,
 1240360: 0,
 1381208: 0,
 1401104: 3,
 1622454: 2,
 1706436: 0,
 1926246: 3,
 1958906: 2,
 1962364: 0,
 2028090: 0,
 2042472: 0,
 2051872: 0,
 2052840: 8,
 2102926: 0,
 2122824: 0,
 2128420: 0,
 2129136: 0,
 2142572: 0,
 2247594: 0,
 2272480: 1,
 2465070: 8,
 2760652: 5,
 2776458: 0,
 2781844: 0,
 2815244: 0,
 2861216: 1,
 2903266: 4,
 2990790: 0,
 3008340: 0,
 3012868: 0,
 3128388: 0,
 3142498: 0,
 3170318: 0,
 3180160: 8,
 3258202: 4,
 3302590: 0,
 3305956: 0,
 3365272: 1,
 3378724: 0,
 3476168: 0,
 3562222: 0,
 3637508: 0,
 3644270: 0,
 3686072: 1,
 3725688: 0,
 3751590: 1,
 3815382: 0,
 3816152: 0,
 3860260: 0,
 3878166: 0,
 3919480: 1,
 3996560: 0,
 4008090: 5,
 4034102: 0,
 4179688: 0,
 4197454: 0,
 4206878: 1,
 4224934: 0,
 4259522: 0,
 4281220: 0,
 4288278: 1,
 4320896: 0,
 4587688: 0,
 4647750: 0,
 4671200: 0,
 4850694: 0,
 4929052: 8,
 4990420: 2,
 5085396: 0,
 5171258: 0,
 5220270: 3,
 5273298: 0,
 5279526: 3,
 5333200: 0,
 5336266: 0,
 5380440: 0,
 5489066: 0,
 5618472: 0,
 5630056: 0,
 5640056: 0,
 5651994: 0,
 5653818: 0,
 5680818: 0,
 5706204: 0,
 5747174: 0,
 5775520: 0,
 5838732: 0,
 5846604: 3,
 5889078: 0,
 5904820: 2,
 5939488: 0,
 5960598: 1,
 5963002: 0,
 5968290: 2,
 6048522: 0,
 6056562: 0,
 6103658: 2,
 6117982: 0,
 6134472: 4,
 6254122: 0,
 6254206: 0,
 6302090: 0,
 6346662: 0,
 6410470: 0,
 6421740: 1,
 6424168: 1,
 6448802: 1,
 6458398: 0,
 6479290: 0,
 6483976: 0,
 6503522: 0,
 6549172: 3,
 6580404: 3,
 6599382: 0,
 6660248: 1,
 6733342: 2,
 6773976: 0,
 6908932: 0,
 6965534: 0,
 7060464: 0,
 7123798: 0,
 7197110: 0,
 7244824: 1,
 7249046: 1,
 7268642: 1,
 7344854: 0,
 7390572: 0,
 7460906: 0,
 7484928: 0,
 7545446: 0,
 7607336: 2,
 7616006: 0,
 7639726: 0,
 7659738: 0,
 7681152: 0,
 7696052: 0,
 7975272: 0,
 7976170: 0,
 8017026: 0,
 8024978: 3,
 8081778: 0,
 8140664: 0,
 8170908: 0,
 8186038: 0,
 8207738: 5,
 8211964: 0,
 8234352: 0,
 8394842: 0,
 8436624: 0,
 8485832: 0,
 8524918: 3,
 8598640: 0,
 8781124: 0,
 8881504: 2,
 8905420: 0,
 8913182: 0,
 8927614: 0,
 9033426: 0,
 9063604: 0,
 9106912: 0,
 9143254: 2,
 9248322: 1,
 9276990: 3,
 9326458: 0,
 9409814: 0,
 9496558: 1,
 9509272: 2,
 9527156: 1,
 9587918: 0,
 9679902: 0,
 9727892: 0,
 9728812: 3,
 9750256: 2,
 9774998: 0,
 9787962: 0,
 9836556: 3,
 9953974: 0,
 9954854: 1,
 9987564: 1,
 9992904: 2,
 10189024: 0,
 10200608: 0,
 10232376: 0,
 10310156: 0,
 10345224: 2,
 10372718: 1,
 10405976: 0,
 10496110: 0,
 10503036: 2,
 10526762: 0,
 10530538: 2,
 10545206: 1,
 10581744: 0,
 10661844: 0,
 10725168: 0,
 10762578: 0,
 10773758: 1,
 10787988: 0,
 10987810: 0,
 11007452: 0,
 11072428: 1,
 11076256: 0,
 11080474: 0,
 11143700: 0,
 11164560: 1,
 11206572: 1,
 11211298: 4,
 11256342: 0,
 11306742: 0,
 11327010: 0,
 11366650: 1,
 11376182: 3,
 11535904: 0,
 11596410: 0,
 11617802: 0,
 11723470: 0,
 11758330: 0,
 11917696: 0,
 12121350: 1,
 12164550: 0,
 12208840: 1,
 12426740: 0,
 12490408: 0,
 12505280: 0,
 12593822: 1,
 12698376: 0,
 12710724: 0,
 12804522: 1,
 12819864: 2,
 12841592: 0,
 12854638: 1,
 12880156: 6,
 12959874: 0,
 12965030: 1,
 13036598: 1,
 13040942: 0,
 13103090: 2,
 13124596: 0,
 13147682: 1,
 13164838: 8,
 13170480: 0,
 13179054: 1,
 13191706: 3,
 13210618: 0,
 13347750: 0,
 13437254: 0,
 13444354: 0,
 13468850: 3,
 13477636: 0,
 13479688: 0,
 13485368: 0,
 13551702: 0,
 13717212: 1,
 13732144: 1,
 13734206: 1,
 13825496: 0,
 13940698: 0,
 13945044: 1,
 13971452: 0,
 13982326: 0,
 14055102: 0,
 14105186: 1,
 14165154: 1,
 14241710: 0,
 14256208: 0,
 14273796: 0,
 14321920: 0,
 14338776: 0,
 14363016: 0,
 14463578: 0,
 14602674: 0,
 14616682: 0,
 14625002: 1,
 14715126: 0,
 14725572: 0,
 14759972: 0,
 14788138: 0,
 14813590: 0,
 14933332: 0,
 14955604: 2,
 15020884: 3,
 15120020: 0,
 15177886: 1,
 15222288: 0,
 15231122: 1,
 15337114: 0,
 15360494: 5,
 15364876: 0,
 15455378: 0,
 15466394: 0,
 15584890: 2,
 15683126: 0,
 15703904: 0,
 15949680: 0,
 16102156: 0,
 16130194: 1,
 16151184: 2,
 16278296: 1,
 16307402: 0,
 16360158: 0,
 16379482: 0,
 16379814: 0,
 16394962: 0,
 16412676: 0,
 16427258: 7,
 16465088: 0,
 16489238: 0,
 16561396: 0,
 16689158: 0,
 16717930: 0,
 16768212: 0}

In [93]:
#Creating a cumulative count of the total number of times search bar was used by
#users viewing design B (b_search_count) & 
#number of times search bar was used by users viewing design A (a_search_count)
b_search_count = sum(b_user.values())
a_search_count = sum(a_user.values())
print("A search count",a_search_count)
print("B search count",b_search_count)

A search count 266
B search count 231

In [94]:
#Finding the frequency of use of search bar in design B vs 
#frequency of use of search bar in design A
a_size = len(a_user)
b_size = len(b_user)
print(a_size)
print(b_size)
a_search_frequency = a_search_count/a_size
b_search_frequency = b_search_count/b_size
print("A search frequency",a_search_frequency)
print("B search frequency",b_search_frequency)

333
348
A search frequency 0.7987987987987988
B search frequency 0.6637931034482759

Inference :-
1. Users using design A have used search bar more number of times over users using design B
(266 vs 231)
2. Frequency of use of search bar in design A is higher than Frequency of use of search bar in design B
(0.79 vs 0.66) 
Results :-
1. Did more users use the search feature in the new design (B)? 
ANS : NO
2. Did users search more often in the new design (B)?
ANS : NO